import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "../components/Button";
import { SiteLayout } from "../components/SiteLayout";
import data from "../data/advisories.json";
const filters=["ALL","CRITICAL","HIGH","MODERATE","LOW"];
export const Route=createFileRoute("/threat-feed")({head:()=>({meta:[{title:"Threat Feed — PurpleLotus"},{name:"description",content:"Browse recent supply chain security advisories from the GitHub Advisory Database, with affected packages, severity, and links to upstream records."},{property:"og:title",content:"Threat Feed — PurpleLotus"},{property:"og:description",content:"Explore a snapshot of recent open-source supply chain advisories."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:ThreatFeed});
function ThreatFeed(){const [filter,setFilter]=useState("ALL");const [search,setSearch]=useState("");const [limit,setLimit]=useState(20);const rows=useMemo(()=>data.advisories.filter(a=>(filter==="ALL"||a.severity.toUpperCase()===filter)&&(!search||`${a.name} ${a.ecosystem} ${a.ghsa_id} ${a.summary}`.toLowerCase().includes(search.toLowerCase()))),[filter,search]);return <SiteLayout><div className="page-hero"><p className="section-kicker">THREAT INTELLIGENCE / GITHUB ADVISORY DATABASE</p><h1>What’s happening in the ecosystem.</h1><p>Recent advisories affecting open-source packages. This is a repository snapshot, not a live or independently verified feed.</p></div><div className="page-content"><div className="feed-toolbar"><div className="feed-tabs">{filters.map(f=><Button key={f} variant={filter===f?"dark":"outline"} onClick={()=>{setFilter(f);setLimit(20)}}>{f}</Button>)}</div><input aria-label="Search advisories" className="feed-search" placeholder="SEARCH PACKAGES OR ADVISORIES" value={search} onChange={e=>{setSearch(e.target.value);setLimit(20)}} /></div><div className="feed-table-head"><span>PACKAGE</span><span>ECOSYSTEM</span><span>PUBLISHED</span><span>PATCHED</span><span>SEVERITY</span><span/></div><div>{rows.slice(0,limit).map(a=><a href={a.source_url} target="_blank" rel="noreferrer" className="advisory-row" key={a.ghsa_id}><strong>{a.name}</strong><span className="advisory-eco">{a.ecosystem}</span><span className="advisory-date">{a.published.slice(0,10)}</span><span className="advisory-patched">{a.patched_version || "—"}</span><span className="advisory-severity">{a.severity}</span><ArrowUpRight size={16}/></a>)}</div><div className="feed-bottom"><p>SHOWING {Math.min(limit,rows.length)} OF {rows.length} ADVISORIES · SNAPSHOT {data.generated_at.slice(0,10)}</p>{limit<rows.length&&<Button variant="outline" onClick={()=>setLimit(limit+20)}>LOAD MORE ↓</Button>}</div><div className="feed-disclaimer">SOURCE NOTE — These results come from the public GitHub Advisory Database and are presented without independent verification by PurpleLotus. Advisory data may be incomplete, disputed or updated. Confirm affected and patched versions against the linked upstream advisory before taking action.</div><div className="digest"><p className="section-kicker">INCIDENT DIGEST</p><h2>No incident briefing available yet.</h2><p>The source repository’s latest digest contains no verified source links. Check back after a future update; no incident claims are shown without sources.</p></div></div></SiteLayout>}
